mapping:
  - name: file_to_file_endpoint_test1
    source:
      type: file_system
      dir: /workspace/src/sandbox/kul/src/channel/unit_tests/source
    destination:
      type: file_system
      dir: /workspace/src/sandbox/kul/src/channel/unit_tests/destination
    transfer:
      type: file_copy
      waittime: 5
      executions: 1

  - name: file_to_file_endpoint_test2
    source:
      type: file_system
      dir: /workspace/src/sandbox/kul/src/channel/unit_tests/source
    destination:
      type: file_system
      dir: /workspace/src/sandbox/kul/src/channel/unit_tests/destination
    channel:
      type: file_copy
      waittime: 5
      executions: 0

