mapping:
  - name: ft1_to_file_endpoint
    source:
      type: file_system
      dir: /workspace/src/sandbox/demo1
    destination:
      type: file_system
      dir: /workspace/src/sandbox/demo2
    channel:
      type: file_copy
      waittime: 5
      executions: 5

  - name: s3_test2
    source:
      type: file_system
      dir:  /workspace/src/sandbox/demo3
    destination:
      type: s3
      dir: unittestingestor
    channel:
      type: file_copy
      waittime: 5
      executions: 0

  - name: kafka_test2
    source:
      type: file_system
      dir: /workspace/src/sandbox/kul/src/channel/unit_tests/source
    destination:
      type: kafka
      topic: unittesttopic
    transfer:
      type: kafka
      host: localhost
      port: 9092
      filter: "csv"
      waittime: 5
      executions: 0
