from stefanpapp/devenv:latest
LABEL Maintainer="Stefan Papp stefan.papp@data-wizard.net"

RUN apk add --update \
    python3 \
    python3-dev \
    py3-pip \
    build-base \
  && pip3 install awscli
