mapping:
  - name: file_to_file_endpoint_test1
    source:
      type: file_system
      dir: /workspace/src/sandbox/demo1
    destination:
      type: file_system
      dir: /workspace/src/sandbox/demo2
    transfer:
      type: file_copy
      waittime: 5
      executions: 5

  - name: file_to_file_endpoint_test2
    source:
      type: file_system
      dir: /workspace/src/sandbox/demo3
    destination:
      type: file_system
      dir: /workspace/src/sandbox/demo4
    transfer:
      type: file_copy
      waittime: 5
      executions: 0

